### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/wisteria#2]
Version 1

- [x] Live on the interwebs.
- [x] Authentication on live domain.

Functionality

- [x] Proper store syncing.
- [x] Delete events.
- [x] Weekly heatmaps.
- [x] Login and authentication.
- [x] Per-user state.
- [x] ~~Overview heatmap.~~ #6
- [x] ~~Create custom events.~~ #13
- [x] ~~Add/edit/migrate logs.~~ #14 
- [x] ~~Custom event aggregation.~~ #15 
- [x] ~~Milestones.~~ #16 

Styles

- [x] Design palette / language / type.
- [x] Style footer.
- [x] Style navigation.
- [x] Style /feed.
- [x] Style /status.
- [x] ~~Style /home.~~ #9
- [x] ~~Cute icon.~~ #10

Setup

- [x] ~~Connect to GitHub.~~ #7
- [x] ~~Connect or import from BB.~~ #8
